spring.datasource.url = jdbc:postgresql://localhost:5432/taskManagement
spring.datasource.username = postgres
spring.datasource.password = S@h1nsah1n
spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto=update